<?php

namespace Modules\Product\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Modules\Product\Models\Product;

class ProductDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Classic Burger',
                'description' => 'Juicy beef patty with lettuce, tomato, onion, and special sauce',
                'sku' => 'BURG-001',
                'price' => 12.99,
                'purchase_price' => 5.50,
                'sale_price' => null,
                'stock' => 100,
                'low_stock_threshold' => 10,
                'status' => 'active',
                'is_featured' => true,
                'product_type' => 'food',
            ],
            [
                'name' => 'Cheese Pizza',
                'description' => 'Traditional pizza with mozzarella cheese and tomato sauce',
                'sku' => 'PIZZ-001',
                'price' => 15.99,
                'purchase_price' => 6.00,
                'sale_price' => 13.99,
                'stock' => 50,
                'low_stock_threshold' => 5,
                'status' => 'active',
                'is_featured' => true,
                'product_type' => 'food',
            ],
            [
                'name' => 'Caesar Salad',
                'description' => 'Fresh romaine lettuce with Caesar dressing, croutons, and parmesan',
                'sku' => 'SALD-001',
                'price' => 9.99,
                'purchase_price' => 3.50,
                'sale_price' => null,
                'stock' => 75,
                'low_stock_threshold' => 10,
                'status' => 'active',
                'is_featured' => false,
                'product_type' => 'food',
            ],
            [
                'name' => 'Grilled Chicken Sandwich',
                'description' => 'Tender grilled chicken breast with avocado and honey mustard',
                'sku' => 'SAND-001',
                'price' => 11.49,
                'purchase_price' => 4.50,
                'sale_price' => null,
                'stock' => 60,
                'low_stock_threshold' => 8,
                'status' => 'active',
                'is_featured' => false,
                'product_type' => 'food',
            ],
            [
                'name' => 'French Fries',
                'description' => 'Crispy golden fries with sea salt',
                'sku' => 'SIDE-001',
                'price' => 4.99,
                'purchase_price' => 1.50,
                'sale_price' => 3.99,
                'stock' => 200,
                'low_stock_threshold' => 20,
                'status' => 'active',
                'is_featured' => false,
                'product_type' => 'food',
            ],
            [
                'name' => 'Chocolate Milkshake',
                'description' => 'Creamy chocolate milkshake topped with whipped cream',
                'sku' => 'DRNK-001',
                'price' => 6.49,
                'purchase_price' => 2.00,
                'sale_price' => null,
                'stock' => 80,
                'low_stock_threshold' => 10,
                'status' => 'active',
                'is_featured' => true,
                'product_type' => 'beverage',
            ],
            [
                'name' => 'Iced Coffee',
                'description' => 'Refreshing cold brew coffee served over ice',
                'sku' => 'DRNK-002',
                'price' => 4.99,
                'purchase_price' => 1.20,
                'sale_price' => null,
                'stock' => 150,
                'low_stock_threshold' => 15,
                'status' => 'active',
                'is_featured' => false,
                'product_type' => 'beverage',
            ],
            [
                'name' => 'BBQ Ribs',
                'description' => 'Slow-cooked pork ribs with tangy BBQ sauce',
                'sku' => 'MAIN-001',
                'price' => 22.99,
                'purchase_price' => 10.00,
                'sale_price' => 19.99,
                'stock' => 30,
                'low_stock_threshold' => 5,
                'status' => 'active',
                'is_featured' => true,
                'product_type' => 'food',
            ],
            [
                'name' => 'Veggie Wrap',
                'description' => 'Fresh vegetables wrapped in a whole wheat tortilla',
                'sku' => 'WRAP-001',
                'price' => 8.99,
                'purchase_price' => 3.00,
                'sale_price' => null,
                'stock' => 45,
                'low_stock_threshold' => 8,
                'status' => 'active',
                'is_featured' => false,
                'product_type' => 'food',
            ],
            [
                'name' => 'Cheesecake',
                'description' => 'New York style cheesecake with strawberry topping',
                'sku' => 'DSRT-001',
                'price' => 7.99,
                'purchase_price' => 2.50,
                'sale_price' => null,
                'stock' => 25,
                'low_stock_threshold' => 5,
                'status' => 'active',
                'is_featured' => true,
                'product_type' => 'dessert',
            ],
            [
                'name' => 'Onion Rings',
                'description' => 'Crispy battered onion rings',
                'sku' => 'SIDE-002',
                'price' => 5.49,
                'purchase_price' => 1.80,
                'sale_price' => null,
                'stock' => 90,
                'low_stock_threshold' => 10,
                'status' => 'active',
                'is_featured' => false,
                'product_type' => 'food',
            ],
            [
                'name' => 'Lemonade',
                'description' => 'Freshly squeezed lemonade',
                'sku' => 'DRNK-003',
                'price' => 3.99,
                'purchase_price' => 0.80,
                'sale_price' => null,
                'stock' => 120,
                'low_stock_threshold' => 15,
                'status' => 'active',
                'is_featured' => false,
                'product_type' => 'beverage',
            ],
            [
                'name' => 'Fish & Chips',
                'description' => 'Beer-battered fish with crispy chips and tartar sauce',
                'sku' => 'MAIN-002',
                'price' => 16.99,
                'purchase_price' => 7.00,
                'sale_price' => null,
                'stock' => 40,
                'low_stock_threshold' => 8,
                'status' => 'active',
                'is_featured' => false,
                'product_type' => 'food',
            ],
            [
                'name' => 'Ice Cream Sundae',
                'description' => 'Vanilla ice cream with chocolate sauce and sprinkles',
                'sku' => 'DSRT-002',
                'price' => 6.49,
                'purchase_price' => 2.00,
                'sale_price' => 5.49,
                'stock' => 55,
                'low_stock_threshold' => 10,
                'status' => 'active',
                'is_featured' => false,
                'product_type' => 'dessert',
            ],
            [
                'name' => 'Chicken Wings',
                'description' => 'Crispy wings with your choice of sauce (Buffalo, BBQ, or Garlic Parmesan)',
                'sku' => 'APPZ-001',
                'price' => 13.99,
                'purchase_price' => 5.00,
                'sale_price' => null,
                'stock' => 70,
                'low_stock_threshold' => 10,
                'status' => 'active',
                'is_featured' => true,
                'product_type' => 'food',
            ],
            [
                'name' => 'Lobster Roll',
                'description' => 'Fresh Maine lobster in a buttered roll',
                'sku' => 'MAIN-003',
                'price' => 28.99,
                'purchase_price' => 15.00,
                'sale_price' => null,
                'stock' => 5,
                'low_stock_threshold' => 10,
                'status' => 'active',
                'is_featured' => true,
                'product_type' => 'food',
            ],
            [
                'name' => 'Seasonal Special',
                'description' => 'Limited time seasonal dish',
                'sku' => 'SPEC-001',
                'price' => 19.99,
                'purchase_price' => 8.00,
                'sale_price' => null,
                'stock' => 0,
                'low_stock_threshold' => 5,
                'status' => 'active',
                'is_featured' => false,
                'product_type' => 'food',
            ],
            [
                'name' => 'Old Recipe Burger',
                'description' => 'Our original burger recipe (discontinued)',
                'sku' => 'BURG-OLD',
                'price' => 10.99,
                'purchase_price' => 4.50,
                'sale_price' => null,
                'stock' => 0,
                'low_stock_threshold' => 5,
                'status' => 'discontinued',
                'is_featured' => false,
                'product_type' => 'food',
            ],
            [
                'name' => 'Test Product',
                'description' => 'Product for testing purposes',
                'sku' => 'TEST-001',
                'price' => 99.99,
                'purchase_price' => 50.00,
                'sale_price' => null,
                'stock' => 10,
                'low_stock_threshold' => 2,
                'status' => 'inactive',
                'is_featured' => false,
                'product_type' => 'other',
            ],
            [
                'name' => 'Spaghetti Carbonara',
                'description' => 'Classic Italian pasta with creamy egg sauce and crispy bacon',
                'sku' => 'PAST-001',
                'price' => 14.99,
                'purchase_price' => 5.50,
                'sale_price' => null,
                'stock' => 65,
                'low_stock_threshold' => 10,
                'status' => 'active',
                'is_featured' => false,
                'product_type' => 'food',
            ],
        ];

        foreach ($products as $productData) {
            Product::create([
                'uuid' => Str::uuid(),
                'name' => $productData['name'],
                'slug' => Str::slug($productData['name']),
                'description' => $productData['description'],
                'sku' => $productData['sku'],
                'price' => $productData['price'],
                'purchase_price' => $productData['purchase_price'],
                'sale_price' => $productData['sale_price'],
                'stock' => $productData['stock'],
                'low_stock_threshold' => $productData['low_stock_threshold'],
                'status' => $productData['status'],
                'is_featured' => $productData['is_featured'],
                'product_type' => $productData['product_type'],
                'pre_order' => false,
                'images' => [],
            ]);
        }

        $this->command->info('Created ' . count($products) . ' products.');
    }
}
