<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { ChevronDown, ChevronUp, Wand2 } from 'lucide-vue-next';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Checkbox } from '@/components/ui/checkbox';
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card';
import {
    Collapsible,
    CollapsibleContent,
    CollapsibleTrigger,
} from '@/components/ui/collapsible';
import type { InertiaForm } from '@inertiajs/vue3';
import type { ProductAttribute, Product } from '../../types';

interface VariantFormData {
    sku: string;
    name: string;
    price: number | null;
    purchase_price: number | null;
    sale_price: number | null;
    stock: number;
    low_stock_threshold: number;
    barcode: string;
    weight: number | null;
    is_default: boolean;
    is_active: boolean;
    sort_order: number;
    attribute_value_ids: number[];
}

interface ProductSettings {
    auto_generate_sku?: boolean;
    sku_prefix?: string;
    sku_separator?: string;
    low_stock_threshold?: number;
}

interface Props {
    mode?: 'create' | 'edit';
    attributes?: ProductAttribute[];
    showAttributesOpen?: boolean;
    product?: Product;
    productSettings?: ProductSettings;
}

const props = withDefaults(defineProps<Props>(), {
    mode: 'create',
    attributes: () => [],
    showAttributesOpen: false,
    product: undefined,
    productSettings: () => ({}),
});

const model = defineModel<InertiaForm<VariantFormData>>({ required: true });

// Check if auto-generate SKU is enabled from global settings
const isAutoGenerateEnabled = computed(() => {
    return props.productSettings?.auto_generate_sku ?? true;
});

// Generate SKU from product and variant name using global settings
const generateSku = (variantName?: string) => {
    const separator = props.productSettings?.sku_separator || '-';
    const prefix = props.productSettings?.sku_prefix || '';
    const productPart = props.product?.sku || props.product?.name || 'PROD';
    const variantPart = variantName || model.value.name || '';

    if (!variantPart) return; // Don't generate if no variant name

    // Clean and format: uppercase, replace spaces with separator, remove special chars
    const cleanProduct = productPart.toUpperCase().replace(/\s+/g, separator).replace(/[^A-Z0-9-]/g, '').slice(0, 10);
    const cleanVariant = variantPart.toUpperCase().replace(/\s+/g, separator).replace(/[^A-Z0-9-]/g, '').slice(0, 10);

    const parts = [prefix, cleanProduct, cleanVariant].filter(Boolean);
    model.value.sku = parts.join(separator);
};

// Auto-generate SKU when name changes (only if enabled in settings, in create mode, and if SKU is empty or was auto-generated)
const lastAutoGeneratedSku = ref('');

// Handle name input change for auto-generate SKU
const handleNameInput = (event: Event) => {
    const newName = (event.target as HTMLInputElement).value;
    if (isAutoGenerateEnabled.value && props.mode === 'create' && newName) {
        // Only auto-generate if SKU is empty or matches the last auto-generated one
        if (!model.value.sku || model.value.sku === lastAutoGeneratedSku.value) {
            generateSku(newName);
            lastAutoGeneratedSku.value = model.value.sku;
        }
    }
};

const showAttributesSection = ref(props.showAttributesOpen);

// Computed Set for reactive checkbox state - this is the key for reactivity!
const selectedValueIds = computed(() => new Set(model.value.attribute_value_ids));

// Toggle attribute value selection
const toggleAttributeValue = (valueId: number) => {
    const currentIds = [...model.value.attribute_value_ids];
    const index = currentIds.indexOf(valueId);
    if (index > -1) {
        currentIds.splice(index, 1);
    } else {
        currentIds.push(valueId);
    }
    model.value.attribute_value_ids = currentIds;
};

const activeAttributes = computed(() => {
    return props.attributes.filter(attr => attr.is_active && attr.values?.length);
});

// Select all values for an attribute
const selectAllValues = (attribute: ProductAttribute) => {
    if (!attribute.values) return;
    const currentIds = new Set(model.value.attribute_value_ids);
    attribute.values.forEach(value => {
        currentIds.add(value.id);
    });
    model.value.attribute_value_ids = Array.from(currentIds);
};

// Deselect all values for an attribute
const deselectAllValues = (attribute: ProductAttribute) => {
    if (!attribute.values) return;
    const valueIds = new Set(attribute.values.map(v => v.id));
    model.value.attribute_value_ids = model.value.attribute_value_ids.filter(id => !valueIds.has(id));
};

// Check if all values are selected for an attribute - uses computed Set
const isAllSelected = (attribute: ProductAttribute) => {
    if (!attribute.values || attribute.values.length === 0) return false;
    return attribute.values.every(value => selectedValueIds.value.has(value.id));
};

const formatPriceAdjustment = (price: number) => {
    if (price === 0) return '';
    const sign = price > 0 ? '+' : '';
    return ` (${sign}$${price.toFixed(2)})`;
};
</script>

<template>
    <div class="grid gap-6 lg:grid-cols-3">
        <!-- Main Content -->
        <div class="lg:col-span-2 space-y-6">
            <!-- Basic Info Card -->
            <Card>
                <CardHeader>
                    <CardTitle>Variant Information</CardTitle>
                    <CardDescription>Basic details about the variant</CardDescription>
                </CardHeader>
                <CardContent class="space-y-4">
                    <div class="grid gap-4 sm:grid-cols-2">
                        <div class="space-y-2">
                            <Label for="sku">SKU</Label>
                            <div class="flex gap-2">
                                <Input
                                    id="sku"
                                    v-model="model.sku"
                                    placeholder="e.g., PROD-001-S"
                                    :class="{ 'border-destructive': model.errors.sku }"
                                    class="flex-1"
                                />
                                <Button
                                    type="button"
                                    variant="outline"
                                    size="icon"
                                    @click="generateSku"
                                    title="Generate SKU"
                                >
                                    <Wand2 class="h-4 w-4" />
                                </Button>
                            </div>
                            <p v-if="model.errors.sku" class="text-sm text-destructive">
                                {{ model.errors.sku }}
                            </p>
                        </div>

                        <div class="space-y-2">
                            <Label for="name">Name <span class="text-destructive">*</span></Label>
                            <Input
                                id="name"
                                v-model="model.name"
                                placeholder="e.g., 128GB Black"
                                :class="{ 'border-destructive': model.errors.name }"
                                @input="handleNameInput"
                            />
                            <p v-if="model.errors.name" class="text-sm text-destructive">
                                {{ model.errors.name }}
                            </p>
                            <p class="text-xs text-muted-foreground">
                                Enter the variant name (e.g., "128GB" or "Black")
                            </p>
                        </div>
                    </div>

                    <div class="grid gap-4 sm:grid-cols-2">
                        <div class="space-y-2">
                            <Label for="barcode">Barcode</Label>
                            <Input
                                id="barcode"
                                v-model="model.barcode"
                                placeholder="e.g., 1234567890123"
                            />
                        </div>

                        <div class="space-y-2">
                            <Label for="weight">Weight (kg)</Label>
                            <Input
                                id="weight"
                                :model-value="model.weight ?? undefined"
                                type="number"
                                step="0.01"
                                min="0"
                                placeholder="0.00"
                                @update:model-value="model.weight = $event ? Number($event) : null"
                            />
                        </div>
                    </div>
                </CardContent>
            </Card>

            <!-- Pricing Card -->
            <Card>
                <CardHeader>
                    <CardTitle>Pricing</CardTitle>
                    <CardDescription>Leave empty to use product's base price</CardDescription>
                </CardHeader>
                <CardContent class="space-y-4">
                    <div class="grid gap-4 sm:grid-cols-3">
                        <div class="space-y-2">
                            <Label for="price">Price</Label>
                            <Input
                                id="price"
                                :model-value="model.price ?? undefined"
                                type="number"
                                step="0.01"
                                min="0"
                                placeholder="0.00"
                                @update:model-value="model.price = $event ? Number($event) : null"
                            />
                        </div>

                        <div class="space-y-2">
                            <Label for="purchase_price">Purchase Price</Label>
                            <Input
                                id="purchase_price"
                                :model-value="model.purchase_price ?? undefined"
                                type="number"
                                step="0.01"
                                min="0"
                                placeholder="0.00"
                                @update:model-value="model.purchase_price = $event ? Number($event) : null"
                            />
                        </div>

                        <div class="space-y-2">
                            <Label for="sale_price">Sale Price</Label>
                            <Input
                                id="sale_price"
                                :model-value="model.sale_price ?? undefined"
                                type="number"
                                step="0.01"
                                min="0"
                                placeholder="0.00"
                                @update:model-value="model.sale_price = $event ? Number($event) : null"
                            />
                        </div>
                    </div>
                </CardContent>
            </Card>

            <!-- Inventory Card -->
            <Card>
                <CardHeader>
                    <CardTitle>Inventory</CardTitle>
                    <CardDescription>Stock and inventory settings</CardDescription>
                </CardHeader>
                <CardContent class="space-y-4">
                    <div class="grid gap-4 sm:grid-cols-2">
                        <div class="space-y-2">
                            <Label for="stock">Stock <span class="text-destructive">*</span></Label>
                            <Input
                                id="stock"
                                v-model.number="model.stock"
                                type="number"
                                min="0"
                                required
                                :class="{ 'border-destructive': model.errors.stock }"
                            />
                            <p v-if="model.errors.stock" class="text-sm text-destructive">
                                {{ model.errors.stock }}
                            </p>
                        </div>

                        <div class="space-y-2">
                            <Label for="low_stock_threshold">Low Stock Threshold</Label>
                            <Input
                                id="low_stock_threshold"
                                v-model.number="model.low_stock_threshold"
                                type="number"
                                min="0"
                            />
                        </div>
                    </div>
                </CardContent>
            </Card>

            <!-- Attributes Card (Optional, Collapsible) -->
            <Collapsible v-if="activeAttributes.length" v-model:open="showAttributesSection">
                <Card>
                    <CollapsibleTrigger as-child>
                        <CardHeader class="cursor-pointer hover:bg-muted/50 transition-colors">
                            <div class="flex items-center justify-between">
                                <div>
                                    <CardTitle>Attribute Values (Optional)</CardTitle>
                                    <CardDescription>Link to predefined attributes if needed</CardDescription>
                                </div>
                                <ChevronDown v-if="!showAttributesSection" class="h-5 w-5 text-muted-foreground" />
                                <ChevronUp v-else class="h-5 w-5 text-muted-foreground" />
                            </div>
                        </CardHeader>
                    </CollapsibleTrigger>
                    <CollapsibleContent>
                        <CardContent>
                            <div class="space-y-6">
                                <div v-for="attribute in activeAttributes" :key="attribute.id" class="space-y-3">
                                    <div class="flex items-center justify-between">
                                        <h4 class="font-medium">{{ attribute.name }}</h4>
                                        <Button
                                            type="button"
                                            variant="ghost"
                                            size="sm"
                                            class="h-7 text-xs"
                                            @click="isAllSelected(attribute) ? deselectAllValues(attribute) : selectAllValues(attribute)"
                                        >
                                            {{ isAllSelected(attribute) ? 'Deselect All' : 'Select All' }}
                                        </Button>
                                    </div>
                                    <div class="flex flex-wrap gap-3" :key="`attr-${attribute.id}-${model.attribute_value_ids.join(',')}`">
                                        <div
                                            v-for="value in attribute.values"
                                            :key="`value-${value.id}-${model.attribute_value_ids.includes(value.id)}`"
                                            class="flex items-center space-x-2"
                                        >
                                            <Checkbox
                                                :id="`value-${value.id}`"
                                                :model-value="model.attribute_value_ids.includes(value.id)"
                                                @update:model-value="toggleAttributeValue(value.id)"
                                            />
                                            <label
                                                :for="`value-${value.id}`"
                                                class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer"
                                            >
                                                <span class="flex items-center gap-2">
                                                    <span
                                                        v-if="attribute.type === 'color' && value.color_code"
                                                        class="h-4 w-4 rounded-full border"
                                                        :style="{ backgroundColor: value.color_code }"
                                                    />
                                                    {{ value.label || value.value }}
                                                    <span class="text-muted-foreground text-xs">
                                                        {{ formatPriceAdjustment(value.price_adjustment) }}
                                                    </span>
                                                </span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <p v-if="model.errors.attribute_value_ids" class="text-sm text-destructive mt-2">
                                {{ model.errors.attribute_value_ids }}
                            </p>
                        </CardContent>
                    </CollapsibleContent>
                </Card>
            </Collapsible>
        </div>

        <!-- Sidebar -->
        <div class="space-y-6">
            <!-- Settings Card -->
            <Card>
                <CardHeader>
                    <CardTitle>Settings</CardTitle>
                </CardHeader>
                <CardContent class="space-y-4">
                    <div class="space-y-2">
                        <Label for="sort_order">Sort Order</Label>
                        <Input
                            id="sort_order"
                            v-model.number="model.sort_order"
                            type="number"
                            min="0"
                        />
                    </div>

                    <div class="flex items-center justify-between">
                        <Label for="is_default">Default Variant</Label>
                        <Switch
                            id="is_default"
                            :checked="model.is_default"
                            @update:checked="model.is_default = $event"
                        />
                    </div>

                    <div class="flex items-center justify-between">
                        <Label for="is_active">Active</Label>
                        <Switch
                            id="is_active"
                            :checked="model.is_active"
                            @update:checked="model.is_active = $event"
                        />
                    </div>
                </CardContent>
            </Card>

            <!-- Actions Slot -->
            <slot name="actions" />
        </div>
    </div>
</template>
